version: '3'

services:
  db:
    image: postgres
  instapy-backend:
    build: ./instapy-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./instapy-backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db